//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotorbikesShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaKH { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập họ tên")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập tài khoản")]
        public string TaiKhoan { get; set; }
        [StringLength(20, MinimumLength =6, ErrorMessage ="Độ dài mật khẩu ít nhất 6 ký tự")]
        [Required(ErrorMessage = "Yêu cầu nhập mật khẩu")]
        public string MatKhau { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập địa chỉ")]
        public string DiaChi { get; set; }
        [StringLength(11, MinimumLength = 10, ErrorMessage = "Số điện thoại không đúng")]
        [Required(ErrorMessage = "Yêu cầu nhập số điện thoại")]
        public string SoDienThoai { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập giới tính")]
        public string GioiTinh { get; set; }
        [Required(ErrorMessage = "Yêu cầu nhập ngày sinh")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> NgaySinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
